# Remap prefix
# export TERM=screen-256color

# Prevent escape from acting as meta 
set -sg escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind - split-window -v
bind _ split-window -v -c "#{pane_current_path}"
bind \\ split-window -h
bind | split-window -h -c "#{pane_current_path}"

bind g new-window -c "#{pane_current_path}" lazygit

bind r source-file ~/.tmux.conf

unbind E
bind v send-keys "~/dotfiles/tmux-scripts/start-vim.sh" Enter
bind d send-keys '~/dotfiles/tmux-scripts/tmux-dev.sh' Enter
bind t send-keys "~/dotfiles/tmux-scripts/tmux-dev.sh '/tmp'" Enter
bind e run '~/dotfiles/tmux-scripts/open-file-vim.sh'
bind E run '~/dotfiles/tmux-scripts/open-file-vim.sh --open-realpath'

# Hotkeys
#-------------------------------------------------------#
unbind o
bind o select-layout -o

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -r C-h resize-pane -L 8
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 8
#-------------------------------------------------------#


# Pane colours
#-------------------------------------------------------#
# set inactive/active window styles
set -g window-style 'fg=colour247,bg=colour236'
set -g window-active-style 'fg=colour250,bg=black'
#-------------------------------------------------------#

