" General settings echo "(>^.^<)"

set nocompatible
filetype plugin indent on
set splitright
set nowrap
let mapleader = ","

" Settings
" ========
set rtp+=~/.vim/bundle/Vundle.vim
set number
set encoding=utf-8
set autoread
set autowrite

" Indentation
" ===========
filetype plugin indent on
set sts=4
set ts=4
set sw=4
set expandtab
set autoindent

augroup python_settings
  autocmd!
  autocmd FileType pytho nsetlocal ts=4 sts=4 sw=4 expandtab autoindent
  autocmd FileType python syn keyword Self self | highlight def link Self Special
augroup END

augroup AddCursorLine
	autocmd!
	autocmd BufEnter,WinEnter * setlocal cursorline
	autocmd BufLeave,WinLeave * setlocal nocursorline
augroup end

augroup BgHighlight
    autocmd!
    autocmd WinEnter,BufRead * set nu rnu
    autocmd WinLeave * setlocal nonu nornu
augroup END

function! GetLastMessageLine()
    redir => messages_output
    silent! messages
    redir END
    let message_lines = split(messages_output, '\n')
    let last_message_line = message_lines[-1]
    return last_message_line
endfunction

" Gitgutter
" =========
nnoremap gt :GitGutterToggle<cr>
nnoremap gp <Plug>(GitGutterPreviewHunk)
nnoremap gu <Plug>(GitGutterUndoHunk)

nnoremap <leader>w :set wrap!<CR>
nnoremap <leader>r :checktime<CR>:so $MYVIMRC<CR>
nnoremap <leader>v :vsplit $MYVIMRC <CR>
nnoremap <leader>b :Isort <cr> :Black <cr>
nnoremap <leader>/ :set hlsearch!<CR>
nnoremap <leader>j J

function! GetLastMessageLine()
    let message_lines = split(execute('messages'), '\n')
    let last_message_line = message_lines[-1]
    return last_message_line
endfunction

nnoremap <leader>pi A  # pylint: disable=<Esc>:execute "normal! a" . split(GetLastMessageLine(), ":")[0]<CR>



nnoremap <key> :let @a=GetLastMessageLine()<CR>
nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
nnoremap <leader>tmp :e /tmp/tmp.py<CR>
nnoremap <leader>tmv :vsplit /tmp/tmp.py<CR>
nnoremap <leader>ntz :NERDTreeClose<cr>:let g:NERDTreeWinSize=62<cr>:NERDTree<cr>
nnoremap <leader>ntr :NERDTreeClose<cr>:let g:NERDTreeWinSize=31<cr>:NERDTree<cr>
nnoremap <leader>S :SlimeConfig<cr>default<cr>1
nnoremap <leader>c :let @+ = expand('%')<cr>


" lua require('leap').add_default_mappings()

" INSERT MAPS
" ===========
inoremap jk <ESC>
inoremap JK <ESC>
inoremap Jk <ESC>
inoremap jK <ESC>
inoremap >> <Plug>(copilot-next)
inoremap << <Plug>(copilot-previous)

" CLIPBOARD
" =========
vnoremap <leader>j "+p
vnoremap <leader>d "+d
vnoremap <leader>y "+y
nnoremap <leader>p "+p
nnoremap <leader>d "+d
nnoremap <leader>y "+y

" vmaps
" =====
vnoremap <leader>rl y:s/<C-R>"//g<left><left>
vnoremap <leader>rg y:%s/<C-R>"//g<left><left>
vnoremap <leader>rc y:%s/<C-R>"//gc<left><left><left>
vnoremap <leader>ry :s/<C-R>"//g<left><left>

vnoremap <leader>ofr sopen(x, 'r')<esc>Fxvp
vnoremap <leader>ofw sopen(x, 'w')<esc>Fxvp
vnoremap <leader>ofa sopen(x, 'a')<esc>Fxvp
vnoremap <leader>ofbr sopen(x, 'rb')<esc>Fxvp
vnoremap <leader>ofbw sopen(x, 'wb')<esc>Fxvp
vnoremap <leader>ofba sopen(x, 'ab')<esc>Fxvp

vnoremap <leader>enum senumerate()<esc>P?for\s<cr>3lai, <esc>/enumerate<cr>
vnoremap <leader>arg xmai()<esc>P`ai
vnoremap <leader>next snext(iter(<esc>pa))<esc>
vnoremap <leader>fmtoff dO# fmt: off<cr># fmt: on<esc>P
vnoremap <leader>try Itry:<cr><esc>oexcept:<cr>__import__("pdb").set_trace() #TODO delme<esc>

" vnoremap <leader>pytarg >O<esc>I<cr><cr><cr>def main(args):<esc>ggOfrom argparse import ArgumentParser<esc>Go<esc>I<cr><cr>if __name__ == "__main__":<cr>parser = ArgumentParser()<cr># parser.add_argument('arg')<cr># parser.add_argument('--kwarg')<cr><cr>main(parser.parse_args())<esc>`ai<tab>
vnoremap <leader>ifmain >O<esc>Iif __name__ == "__main__":<cr>main()


" Always use visual lines vim
" ===========================
nmap k gk
nmap j gj


" Turbomove
" =========
nnoremap J 5j
nnoremap K 5k
nnoremap L 5l
nnoremap H 5h
vnoremap J 5j
vnoremap K 5k
vnoremap L 5l
vnoremap H 5h

iabbr slef self

iabbr bp __import__("pdb").set_trace() #TODO delme
iabbr sysexit __import__("sys").exit() #TODO delme
iabbr pytargs <esc>I<cr><cr><cr>def main(args):<esc>ggOfrom argparse import ArgumentParser<esc>Go<esc>I<cr><cr>if __name__ == "__main__":<cr>parser = ArgumentParser()<cr># parser.add_argument('arg')<cr># parser.add_argument('--kwarg')<cr><cr>main(parser.parse_args())<esc>`ai<tab>

iabbr class classz():<esc>?z<cr>xi
iabbr def defz():<esc>?z<cr>xi
iabbr cdef defz(self, ):<esc>?z<cr>xi
iabbr ifmain if __name__ == "__main__":<cr>
iabbr definit def __init__(self,z):<esc>?z<cr>xi
iabbr superinit super().__init__()

iabbr imnp import numpy as np
iabbr implt import matplotlib.pyplot as plt
iabbr impl import pytorch_lightning as pl


" Plugins
" =======
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'voldikss/vim-floaterm'
Plugin 'jpalardy/vim-slime' " Plugin 'vim-slime'
Plugin 'kdheepak/lazygit.nvim'
Plugin 'vim-scripts/indentpython.vim' " Proper indentation
Plugin 'unblevable/quick-scope' " Highligt first unique letter
Plugin 'morhetz/gruvbox' " Colorscheme
Plugin 'junegunn/fzf', { 'do': './install --bin' } " Rg
Plugin 'junegunn/fzf.vim' "fzf
Plugin 'junegunn/vim-easy-align'
Plugin 'psf/black' " Black
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat' " Let Vim Surround repeat actions
Plugin 'tpope/vim-fugitive'
Plugin 'dense-analysis/ale'
Plugin 'Krasjet/auto.pairs' " autocompletion of paranthesis
Plugin 'airblade/vim-gitgutter'
Plugin 'preservim/nerdcommenter' " Comment
Plugin 'preservim/nerdtree' " Comment
Plugin 'fisadev/vim-isort'
Plugin 'nvim-tree/nvim-web-devicons' " optional, for file icons
Plugin 'github/copilot.vim'
" Plugin 'Valloric/YouCompleteMe' " Autocompletion and jump to definition
Plugin 'vim-airline/vim-airline'
"
call vundle#end()
" Unused
" Plugin 'nvim-tree/nvim-tree.lua'
" Plugin 'SirVer/ultisnips'
" Plugin 'honza/vim-snippets'
" Plugin 'ggandor/leap.nvim'
" Plugin 'neovim/nvim-lspconfig'


" ALE
" ===
nnoremap - :ALENext<cr>
nnoremap _ :ALEPrevious<cr>


" YouCompleteMe
" =============
nnoremap <C-B> :YcmCompleter GoToDeclaration <CR>
" let g:ycm_goto_buffer_command = 'new-tab'
" let g:ycm_auto_trigger=1
" let g:ycm_autoclose_preview_window_after_insertion = 1


" SnipMate
let g:UltiSnipsExpandTrigger="<TAB>"


" Easy Align
" ==========
vnoremap <leader>ga <Plug>(EasyAlign)*

" Slime
" =====
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": 1}

" Gruvbox
" =======
colorscheme gruvbox
set background=dark
set t_Co=256

" FZF/rg
" ======
nnoremap <leader>f :Files <CR>
nnoremap + :Buffers<cr>
nnoremap <leader>s :Rg <CR>

" Nerd commenter
" ==============
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDTrimTrailingWhitespace = 1
let g:NERDCommentBadWhitespace = 1
vnoremap <C-x> <Plug>NERDCommenterToggle
nnoremap <C-x> <Plug>NERDCommenterToggle

" Nerd tree
" =========
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:NERDTreeShowHidden = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeDirArrows = 1
"
" LazyGit
" =======
let g:lazygit_floating_window_winblend = 0 " transparency of floating window
let g:lazygit_floating_window_scaling_factor = 0.9 " scaling factor for floating window
let g:lazygit_floating_window_corner_chars = ['╭', '╮', '╰', '╯'] " customize lazygit popup window corner characters
let g:lazygit_floating_window_use_plenary = 0 " use plenary.nvim to manage floating window if available
let g:lazygit_use_neovim_remote = 1 " fallback to 0 if neovim-remote is not installed


" GitGutter
" =========
let g:gitgutter_enabled = 0


" FZF
" ===
let $FZF_DEFAULT_COMMAND='rg --files'
command! -bang -nargs=? -complete=dir Files call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}), <bang>0)
let g:fzf_preview_window = ['right:50%', 'ctrl-/']


" Jedi
" ====
" Plugin 'davidhalter/jedi-vim'
" let g:jedi#show_call_signatures = "1"
" let g:jedi#popup_on_dot = "0"
" let g:jedi#goto_command = ""
" let g:jedi#goto_assignments_command = ""
" let g:jedi#goto_stubs_command = ""
" let g:jedi#goto_definitions_command = ""
" let g:jedi#usages_command = ""
" let g:jedi#completions_command = ""
" let g:jedi#rename_command = "<leader>R"
" let g:jedi#documentation_command = "<leader>h"


" Have persistent undo in vim
" ===========================
let vimDir = '$HOME/.vim'

if stridx(&runtimepath, expand(vimDir)) == -1
  let &runtimepath.=','.vimDir
endif
if has('persistent_undo')
	let myUndoDir = expand(vimDir . '/undodir')
	:silent call system('mkdir ' . vimDir)
	:silent call system('mkdir ' . myUndoDir)
	let &undodir = myUndoDir
	set undofile
endif


syntax on
