language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install pre-commit
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6'* ]]; then pre-commit run -a; fi
  - python setup.py test
